build:
  maxIssues: 0 # Fail the build if any issues are found

style:
  WildcardImport:
    active: true
    excludes: ['kotlinx.android.synthetic.*']

  NamingConventionViolation:
    active: true
    variablePattern: '^[a-z][a-zA-Z0-9]*$'
    constantPattern: '^[A-Z][_A-Z0-9]*$'
    methodPattern: '^[a-z][a-zA-Z0-9]*$'
    classPattern: '^[A-Z][a-zA-Z0-9]*$'
    enumEntryPattern: '^[A-Z][_A-Z0-9]*$'

  MagicNumber:
    active: true
    ignoreNumbers: ['-1', '0', '1', '2'] # Numbers which do not count as 'magic numbers'

performance:
  UnusedImports:
    active: true

complexity:
  LongMethod:
    active: true
    threshold: 15

  LongParameterList:
    active: true
    threshold: 5

  LargeClass:
    active: true
    threshold: 150

potential-bugs:
  LateinitUsage:
    active: true
    excludeAnnotatedProperties: 'Inject, Mock'

  UnsafeCallOnNullableType:
    active: true

comments:
  CommentOverPrivateFunction:
    active: false # You might want to allow private functions without comments

  CommentOverPrivateProperty:
    active: false # You might want to allow private properties without comments

formatting:
  MaxLineLength:
    active: true
    maxLineLength: 120

  Indentation:
    active: true
    indentSize: 4
    continuationIndentSize: 4

exceptions:
  SwallowedException:
    active: true
    allowedExceptionNameRegex: '^(ignore|expected).*'

empty-blocks:
  EmptyFunctionBlock:
    active: true
